version: '3'

volumes:
  pg_data:
  static_value:
  media_value:


services:
  postgres:
    image: postgres:13.10
    environment:
      POSTGRES_DB: kittygram
      POSTGRES_USER: kittygram_user
      POSTGRES_PASSWORD: kittygram_password
    volumes:
      - pg_data:/var/lib/postgresql/data/

  backend:
    image: vladislavgs/kittygram_backend:latest
    env_file: .env
    depends_on:
      - postgres
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/    

  frontend:
    image: vladislavgs/kittygram_frontend:latest
    env_file: .env
  
  gateway:
    image: vladislavgs/kittygram_gateway:latest
    ports:
      - "80:80"
    volumes:
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend
      - frontend
