version: '3'

volumes:
  pg_data:
  static:
  media:
  frontend_build:

services:
  postgres:
    image: postgres:13
    env_file:
      - .env
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data/

  backend:
    image: vladislavgs/kittygram_backend:latest
    env_file: .env
    restart: always
    depends_on:
      - postgres
    volumes:
      - static:/app/collected_static/
      - media:/app/media/    

  frontend:
    image: vladislavgs/kittygram_frontend:latest
    env_file: .env
    restart: always
    volumes:
      - frontend_build:/app/build/
  
  gateway:
    image: vladislavgs/kittygram_gateway:latest
    ports:
      - "80:80"
    restart: always
    volumes:
      - frontend_build:/usr/share/nginx/html/
      - static:/var/html/static/
      - media:/var/html/media/
    depends_on:
      - backend
      - frontend
