FROM python:3.9

WORKDIR /app
RUN apt-get update && apt-get install -y netcat-openbsd \
    && rm -rf /var/lib/apt/lists/*
COPY requirements.txt .
RUN pip install -r requirements.txt --no-cache-dir
COPY . .
# CMD ["python", "manage.py", "runserver", "0.0.0.0:9000"]