#cloud-config

ssh_pwauth: no

users:
  - name: ${USER}
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh-authorized-keys:
    - "${SSH_KEY}"

write_files:
  - path: "/root/vm_require.sh"
    permissions: "0744"
    content: |
      #!/bin/bash
      set -e
      apt-get update
      apt-get install -y docker.io
      systemctl enable docker
      systemctl start docker
      usermod -aG docker ${USER}

runcmd:
  - sleep 120
  - sudo /root/vm_require.sh
